<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="LAPTOP-RDKSQOER" name="com.qa.pages.HandleTheExceptionTest" tests="3" failures="0" timestamp="2022-06-23T22:56:07 IST" time="0.018" errors="0">
  <testcase name="nullPointerException" time="0.001" classname="com.qa.pages.HandleTheExceptionTest"/>
  <system-out/>
  <testcase name="arithmeticException" time="0.014" classname="com.qa.pages.HandleTheExceptionTest"/>
  <system-out/>
  <testcase name="skipTestCase" time="0.003" classname="com.qa.pages.HandleTheExceptionTest">
    <skipped/>
  </testcase> <!-- skipTestCase -->
  <system-out/>
</testsuite> <!-- com.qa.pages.HandleTheExceptionTest -->
